INSERT INTO USER (NAME, USERNAME, PASSWORD, MOBILE_NUMBER, EMAIL, ROLE)
VALUES ('admin', 'admin', 'eft#$@', '09121234567', 'admin@insurance.com', 'ADMIN');
INSERT INTO USER (NAME, USERNAME, PASSWORD, MOBILE_NUMBER, EMAIL, ROLE)
VALUES ('user', 'user', 'ooojknh%&*', '09122345678', 'user@insurance.com', 'USER');
INSERT INTO USER (NAME, USERNAME, PASSWORD, MOBILE_NUMBER, EMAIL, ROLE)
VALUES ('general_user', 'generaluser', '@@@mno###', '09123456789', 'guser@insurance.com', 'GENERAL_USER');

INSERT INTO PRODUCT (CODE, TITLE, TYPE, DESCRIPTION, ENABLE, VISITABLE, REGISTER_COMMENT, REGISTER_VOTE)
VALUES ('P001', 'product', 'COMPUTERS', 'product', 1, 1, 1, 1);